server:
  port: 8011
spring:
  datasource:
    url: jdbc:mysql://47.103.8.71:3306/blog
    username: root
    password: Zz3417567
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  type-aliases-package: com.yufei.entity
  mapper-locations: classpath:mapper/*.xml